### ISSUE TITLE
Wind trumpet in pegasi stables doesn´t work

### ISSUE THREAD

**Issue by AlmondC00kie** [x0xll/sarabella.neocities.org#10]
The trumpet on the left of the screen that (if i remember right) should blow away the dirty leaves on the ground so that you can (along with cleaning the horse) get 100% cleanliness doesn´t work. It plays the music and sounds of wind but doesn´t do anything.

**Comment by Gridloch** [comment]
The trumpet is actually just meant to 'soothe' the horse. The leaves can be blown away using the windchimes, though these are often hidden behind the horse wings which can obviously make them difficult to find (using the help menu can show where it is if it's too hidden).

See this video of the original for comparison https://youtu.be/uaQ2FjKgHKQ?t=1420

**Comment by AlmondC00kie** [comment]
Ohhh okay, sorry for the confusion!! I totally forgot about those
